---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example-cj
  labels:
    app: nginx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example-cj
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example-cj
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: docker.io/twalter/openshift-nginx
        name: nginx
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example-cj
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: nginx
  type: LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-nginx
  namespace: nginx-example-cj
  labels:
    app: nginx
    service: my-nginx
spec:
  to:
    kind: Service
    name: my-nginx
  port:
    targetPort: 8081
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nginx-example-cj
  namespace: nginx-example-cj
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
